### ISSUE TITLE
v4.5.0 spago@next publishing

### ISSUE THREAD

**Issue by jamesdbrock** [xc-jp/purescript-protobuf#43]
I have tagged v4.5.0 but I can't publish it to the Registry yet.

In the meantime I think you can add **protobuf** to [`spago.yaml` dependencies](https://github.com/purescript/spago?tab=readme-ov-file#the-configuration-file) like this:

```yaml
package:
  dependencies:
    - protobuf

workspace:
  packageSet:
    registry: 60.5.1
  extraPackages:
    protobuf:
      git: https://github.com/rowtype-yoga/purescript-protobuf.git
      ref: v4.5.0
      subdir: library
```
